version: '3'
services:
  yard:
    image: yard:$YARD_VERSION
    container_name: yard-$YARD_VERSION
    environment:
      YARD_VERSION: $YARD_VERSION
      PRODUCT_VERSION: $PRODUCT_VERSION
      NEXT_PUBLIC_PRODUCT_VERSION: $PRODUCT_VERSION
      BACKYARD_PORT: 8080
      BACKYARD_HOST: backyard
    ports:
      - "3000:3000"
    networks:
      - app-network
  backyard:
    image: backyard:$BACKYARD_VERSION
    container_name: backyard-$BACKYARD_VERSION
    ports:
      - "8080:8080"
    environment:
      ENCRYPTION_KEY: $ENCRYPTION_KEY
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_PASS: $DB_ENIGMA
      POSTGRES_INIT_DB: $POSTGRES_INIT_DB
      BACKYARD_HOST: 0.0.0.0
      BACKYARD_PORT: 8080
      BACKYARD_VERSION: $BACKYARD_VERSION
      PRODUCT_VERSION: $PRODUCT_VERSION
      LOG_LEVEL: $LOG_LEVEL
      SMTP_PASSWORD: $SMTP_PASSWORD
    networks:
      - app-network
  postgres:
    image: postgres:15.1
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - /opt/backyarddb:/var/lib/postgresql/data

    environment:
      POSTGRES_DB: backyarddb
      POSTGRES_USER: backyard
      POSTGRES_PASSWORD: $DB_ENIGMA
      PRODUCT_VERSION: $PRODUCT_VERSION
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
